### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by RehanSaeed** [tomakita/Colorful.Console#1]
This project is cool and deserves more recognition. I was sad to find that there isn't a NuGet package for it (Or at least I could not find one).

**Comment by tomakita** [comment]
Hi Muhammad,

 

Thanks for the kind words, and thanks for the suggestion!  I’ve just created a NuGet package for Colorful.Console, and will send you another e-mail with the details once I’ve tested it out.  Due to my work schedule, I probably won’t be able to get to it until the weekend.

 

 

Thanks again,

 

Tom

**Comment by RehanSaeed** [comment]
Sounds good. I was going to build the same code so it's nice to see it's out there already. Would you consider contributions for writing Ascii text to the console using [Figlet](https://en.wikipedia.org/wiki/FIGlet) fonts?

**Comment by tomakita** [comment]
Okay, here it is:

https://www.nuget.org/packages/Colorful.Console (you can also use 'Install-Package Colorful.Console' in the Package Manager Console)

I would be very enthusiastic about contributions for Figlet font support!

**Comment by RehanSaeed** [comment]
Sounds good. I'll submit a pull request when I get a chance, I already have the code.

Consider using the new .xproj project templates (An example of my [Boilerplate.Web.Mvc](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/tree/master/Source/MVC6/Boilerplate.Web.Mvc6.Razor)), which compile to NuGet packages and you can target .NET 4 to 4.6.1 and everything inbetween all at once. Also consider adding a few other things to the NuGet package like an icon, and key file. An example of a possible project.json file:

```
{
  "version": "1.0.0",
  "title": "Colorful.Console",
  "description": "...",
  "releaseNotes": "First Release.",
  "authors": [ "Tokakita" ],
  "owners": [ "Tokakita" ],
  "copyright": "@ Tokakita. All rights Reserved",
  "tags": [ "Colourful", "Colorful", "Console", "Command", "Line", "ASCII", "Art", "Figlet" ],
  "iconUrl": "https://example.com/Icon.png",
  "projectUrl": "http://colorfulconsole.com/",
  "licenseUrl": "http://colorfulconsole.com//LICENSE",
  "requireLicenseAcceptance": true,

  "compilationOptions": {
    "keyFile": "../../Key.snk"
  },

  "dependencies": {
  },

  "frameworks": {
    "net4": { },
    "net45": { },
    "net451": { },
    "net452": { },
    "net46": { },
    "net461": { }
  }
}
```

**Comment by tomakita** [comment]
Cool, thanks Muhammad.  I'm going to learn more about these xproj project templates, and will work on this.  I'm still fairly inexperienced at a lot of this, so the suggestions are very much appreciated.
