### ISSUE TITLE
breaks if I loop through colors

### ISSUE THREAD

**Issue by bryans2k** [tomakita/Colorful.Console#10]
this seems to break it as it stops changing the text color.

foreach (var color in GetColors())
{
Console.WriteLine($"{color.Name,-20}", color)
}

**Comment by tomakita** [comment]
Thanks for bringing this to my attention.  Without seeing the definition of the GetColors() method that's being called, I would guess that you're trying to iterate through (and write to the console using) more than 16 colors.  See below, taken from colorfulconsole.com:

"Colorful.Console can only write to the console in 16 different colors (including the black that's used as the console's background, by default!) in a single console session. This is a limitation of the Windows console itself, and it's one that I wasn't able to work my way around. If you know of a workaround, let me know! "

Does this sound like it might be the problem?

**Comment by bryans2k** [comment]
Yeah, sorry that's it. I misunderstood the library.

Bryan Brinegar

On May 20, 2016, at 6:22 PM, Tom Akita <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for bringing this to my attention. Without seeing the definition of the GetColors() method that's being called, I would guess that you're trying to iterate through (and write to the console using) more than 16 colors. See below, taken from colorfulconsole.com<http://colorfulconsole.com>:

"Colorful.Console can only write to the console in 16 different colors (including the black that's used as the console's background, by default!) in a single console session. This is a limitation of the Windows console itself, and it's one that I wasn't able to work my way around. If you know of a workaround, let me know! "

Does this sound like it might be the problem?

-

**Comment by tomakita** [comment]
No problem.  Feel free to open another issue any time!
