### ISSUE TITLE
WriteLineFormatted does not work

### ISSUE THREAD

**Issue by NerijusN** [tomakita/Colorful.Console#17]
```
private static readonly Formatter[] ResponseFormatter = {
   new Formatter("BBD",  Color.DeepPink)
};
```
then usage:
```
Colorful.Console.WriteLineFormatted($"■ result BBD", Color.LightGray, ResponseFormatter);
```
does not color 'BBD' as expected.

**Comment by tomakita** [comment]
Apologies for the extremely tardy reply -- I haven't been spending as much time on this project as I should!

It looks like `WriteLineFormatted `is being used in a slightly incorrect way in your example.  `WriteLineFormatted ` is takes a _formatted_ string as its `format` parameter.  This means that if your example is changed to the following, it should work:
```
// No change needed here.
private static readonly Formatter[] ResponseFormatter = {
   new Formatter("BBD",  Color.DeepPink)
};

// Here is the change (note the absence of the '$', and the replacement of the 'BDD' literal with '{0}')
Colorful.Console.WriteLineFormatted("■ result {0}", Color.LightGray, ResponseFormatter);
```
Let me know how this goes if you try it.  Sorry again for the delay!
