### ISSUE TITLE
Bug in FigletFont

### ISSUE THREAD

**Issue by Iain-Stevenson** [tomakita/Colorful.Console#19]
I just wanted to put this on as a potential problem and solution for anyone else interested.

When I modified the example to Show WriteAscii it showed that the FigletFont setup is hit by a bug.

 
```
public static FigletFont Parse(string fontContent)
        {
            if (fontContent == null) { throw new ArgumentNullException(nameof(fontContent)); }

            return Parse(fontContent.Split(new string[] { Environment.NewLine }, StringSplitOptions.None));
        }

```

Is passing a single string not an array to 

`public static FigletFont Parse(IEnumerable<string> fontLines)`

 and Font.Lines[] gets only 1 item instead of hundreds. After which it all goes very badly.

When I changed it from;

`fontContent.Split(new string[] { Environment.NewLine }, StringSplitOptions.None)`

to;

`fontContent.Split( new char[] { '\r','\n' }, StringSplitOptions.None)`

It worked! I think this may be a bug in the .NET Core framework behind this. 

So watch out folks

**Comment by tomakita** [comment]
Thanks for the report.  May I ask which OS you were running this on?

**Comment by Iain-Stevenson** [comment]
The solution I ran was directly downloaded on the day of the OP.
The .NET frameworks were as specified in the repository project.json's for the solution.
It build as expected, and requested framework versions were honored.

All tests pass except (es expected)

`MapColor_ThrowsException_WhenCalledAndConsoleWindowIsntOpen`

It showed up when I un-commented this line and ran the Console example

`Console.WriteAscii("Hello World");`

On top of this issue I was also experiencing color matching issues with 

`Console.WriteAsciiAlternating("Hello World", new FrequencyBasedColorAlternator(2, Color.Green, Color.White));`

but I will report on that in more detail separately when I get a moment because the colors did not alternate. 

I am wondering about 2 possible causes.

1 The rapidly changing nature of .NET core at this point in its evolution.
2 The LTSB version of the OS 

If the LTSB branch is the cause its the first problem I have encountered with LTSB for anything.

For completeness here's my technical environment. Let me know if you need any other information.

Abstract from SysInfo

> This is on a Surface Pro 4
> Installed Physical Memory (RAM)	16.0 GB	
> OS Name	Microsoft Windows 10 Enterprise N 2015 LTSB	
> Version	10.0.10240 Build 10240	
> System Manufacturer	Microsoft Corporation	
> System Model	Surface Pro 4

Abstract from VS About

> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework Version 4.6.01055
> Visual C# 2015   00322-90150-01716-AA595
> JetBrains ReSharper Ultimate 2016.3.2    Build 107.0.20170126.120331
> Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
> NuGet Package Manager   3.5.0

**Comment by Iain-Stevenson** [comment]
I pretty sure I know what the problem is. I did some more digging. Its not the .NET  Core framework and its not my OS AFAIK. 

Using the visual studio binary  editor and Notepad++ to be sure on DefaultFonts.cs I noticed that the lines of the downloaded class (all of them are the same) are terminated with only the line feed '\n' character on my system. It also has a BOM at the start of the file of 'EF BB BF' (UTF-8)

Its a mismatch between what the OS says should happen and what actually happens with these files.

Solution files originating from my system are '\r\n' terminated.

I think this may be a Git settings problem.

When the source is downloaded to me it preserves what is in the repository.  I am guessing here that your source files are '\r\n' terminated on your machine(s) and '\n' terminated in GitHub.

So I get '\n' terminated files. My system via `Environment.NewLine` says they should be '\r\n' terminated so it goes wrong.

**Comment by Iain-Stevenson** [comment]
I just downloaded the files via Git clone and the files turned up with '\r'\n' terminated lines.

So this is an artifact of the Download via Zip file that is behind the problem. I shall have to watch out for that one in future.

**Comment by tomakita** [comment]
Thanks for the very detailed info, and for finding the root of the issue!  It seems that we can control the line endings that are inserted during the "Download via Zip" process in the .gitattributes file.  The only problem is that setting line endings to "\r\n" in that file would break the DefaultFont.cs file for Unix users who Download via Zip.

I'll see if I can come up with a workaround for this tonight.

**Comment by tomakita** [comment]
Thinking more about it, it seems like your solution of changing

`fontContent.Split(new string[] { Environment.NewLine }, StringSplitOptions.None)`

to

`fontContent.Split(new string[] { "\r", "\n" }, StringSplitOptions.RemoveEmptyEntries)`

may be just what we need.  I used `StringSplitOptions.RemoveEmptyEntries` because empty entries would be included in the resulting string array if this were to be run on a file with "\r\n" line endings.  I can't think of any serious drawbacks to doing the parsing this way, but figured I would run this by you before committing.  Does this seem sensible?

**Comment by Iain-Stevenson** [comment]
I agree a common solution for Windows/Unix is needed and from however the code is obtained. I shall give your idea a test here with either line ending type just to make sure  and let you know.

**Comment by Iain-Stevenson** [comment]
Yep, works like a charm. 

I tested on both of the project copies I have and it solves the problem and I think its probably the best way to handle the windows/unix tension wrt line endings.

I had never bumped into this line termination problem before. I shall have to forget something about Windows 3.1 programming or DOS batch scripts or something even less useful now to make room for it in my head. :-)

Thanks for the hard work putting this together, very useful utility.

**Comment by tomakita** [comment]
Great, I've just committed this change.  I've also never come across this problem before -- maybe partly because whitespace gets ignored in most of the stuff I download from GitHub.  Anyway, thanks a lot for the help with this! 

And be careful, you never know when Windows 3.1 knowledge will come in handy ;)
