### ISSUE TITLE
Error with new colors as a default arguement

### ISSUE THREAD

**Issue by ATMunnGit** [tomakita/Colorful.Console#20]
I have a method that draws a single character anywhere on the screen. I want you to be able to specify colors, however, I also want the default color to be white. This is what I have:

`public void draw(int x, int y, string text, Color color = Color.White) `

It gives me this error:

> Default parameter value for 'color' must be a compile-time constant

Any way around this?

**Comment by midianok** [comment]
The best way to implement such behaviour, is use overload

```cs
public void draw(int x, int y, string text) //default white color
{
	draw(x, y, text, Color.White);
}

public void draw(int x, int y, string text, Color color)
{
	//you code
}
```

**Comment by tomakita** [comment]
@ATMunnGit 
Thanks for the question.  Is midianok's solution acceptable?  If not, we can discuss other ways.

**Comment by ATMunnGit** [comment]
@tomakita 
Yep, that will work.
