### ISSUE TITLE
Foreground color reverts to default after resume from sleep

### ISSUE THREAD

**Issue by ptr727** [tomakita/Colorful.Console#25]
Hi, using nuget version 1.0.7.0 on Win 10 x64.
C# .NET console app created with Visual Studio 2017 Enterprise.
Console produces text every few seconds.
Machine went to sleep, when I woke the machine up, the console started painting in the default color.

**Comment by tomakita** [comment]
Thanks for reporting this.  I suppose Windows doesn't save the color table of the console screen buffer [(MSDN)](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682091(v=vs.85).aspx) when it sleeps.  

Off the top of my head, the only way to address this would be to save the state of the color table to disk at certain times (perhaps each time it's written to), and then load them when Windows wakes up [(on power mode change)](https://msdn.microsoft.com/en-us/library/microsoft.win32.systemevents.powermodechanged.aspx).

I don't have plans to implement this at the moment, but will keep it in mind for the future.  Thanks again for reporting!
