### ISSUE TITLE
Colors stuck after 16 quick changes

### ISSUE THREAD

**Issue by rushfrisby** [tomakita/Colorful.Console#31]
I am creating an app to mimic [lolcat](https://github.com/busyloop/lolcat) in Windows but am testing with random colors first. The library stops swapping colors after 16 characters however. Is there something I am doing wrong or is this a bug?

**Gist**
https://gist.github.com/rushfrisby/da85bc690fcfbc669dd5f6b301d1b570

**Screenshot**
![image](https://user-images.githubusercontent.com/574729/27520858-598d54fe-59e2-11e7-8ea9-6b2d6582a481.png)

**Comment by rushfrisby** [comment]
Looks like a limitation of Windows.

**Comment by Klausbdl** [comment]
> Looks like a limitation of Windows.

Any solution?

**Comment by rushfrisby** [comment]
I don't remember off the top of my head. You can check out what I ended up with here https://github.com/rushfrisby/lolcmd

**Comment by Klausbdl** [comment]
Many thanks!
