### ISSUE TITLE
Missing reference to System.Drawing ?

### ISSUE THREAD

**Issue by hephinator** [tomakita/Colorful.Console#34]
Version 1.0.7:
![image](https://user-images.githubusercontent.com/2331387/27701125-f36ada7c-5ccd-11e7-9d77-3fcca8c792f3.png)
(works)

Version 1.1.0: 
![image](https://user-images.githubusercontent.com/2331387/27701351-9ac87e6e-5cce-11e7-92f1-0551cbb87bb7.png)

HOWEVER, as a caveat, if you downgrade to 1.0.7, compile, then upgrade the library to 1.1.0, it will then resolve and add the missing reference assembly?? 

not sure why this happens but its quite hilarious IMO

**Comment by hephinator** [comment]
Just to clarify, you may notice that it says 'color.' instead of "Color." but it was just a typo, problem still remains with the missing assembly :P

**Comment by tomakita** [comment]
Thanks for letting me know.  After much digging, it turns out that this is a NuGet bug that is going to be fixed soon:

https://github.com/NuGet/Home/issues/4853

I can't spend any more time on this tonight, but will come up with a workaround in the next few days.

**Comment by tomakita** [comment]
I've just released an updated package that fixes this:

https://www.nuget.org/packages/Colorful.Console/1.1.1

System.Drawing should now be referenced automatically!  Thanks again for bringing this to my attention!
