### ISSUE TITLE
Where to get working Figlet fonts from?

### ISSUE THREAD

**Issue by IneedHelp** [tomakita/Colorful.Console#35]
Hello, I've tried figlet fonts found here ( https://github.com/xero/figlet-fonts ) but they don;t seem to work at all. Where do we get working figlet fonts from?

In other words, this snippet doesn't output anything, it just generates empty lines:
`FigletFont font = FigletFont.Load("chunky.flf");
Figlet figlet = new Figlet(font);

Console.WriteLine(figlet.ToAscii("Belvedere"), ColorTranslator.FromHtml("#8AFFEF"));
Console.WriteLine(figlet.ToAscii("ice"), ColorTranslator.FromHtml("#FAD6FF"));
Console.WriteLine(figlet.ToAscii("cream."), ColorTranslator.FromHtml("#B8DBFF"));`

**Comment by tomakita** [comment]
Good question!  The fonts in the repo you linked to will be fine -- I haven't tested all of them, of course, but the one's I've looked at seem valid.  Another source is the [FIGlet website](http://www.figlet.org/).  

Anyway, it looks like you're passing the `StyledString` that is returned from `Figlet.ToAscii` to `Console.WriteLine`.  Instead, try transforming that `StyledString` to a `System.String`, first, by accessing `StyledString`'s `ConcreteValue` property:

    FigletFont font = FigletFont.Load("chunky.flf");
    Figlet figlet = new Figlet(font);

    Console.WriteLine(figlet.ToAscii("Belvedere").ConcreteValue, ColorTranslator.FromHtml("#8AFFEF"));
    Console.WriteLine(figlet.ToAscii("ice").ConcreteValue, ColorTranslator.FromHtml("#FAD6FF"));
    Console.WriteLine(figlet.ToAscii("cream.").ConcreteValue, ColorTranslator.FromHtml("#B8DBFF"));

Hopefully that will get you started.

**Comment by IneedHelp** [comment]
Excellent! After some investigation I detected that some font files were not compatible (that is, they were containing data that looked encrypted). Thank you for the help and this wonderful library!
