### ISSUE TITLE
Formatting doesn't work as expected

### ISSUE THREAD

**Issue by IneedHelp** [tomakita/Colorful.Console#36]
Given the code:

`string dream = "a dream of {0} and {1} and {2} and {3} and {4} and {5} and {6} and {7} and {8} and {9}...";
Formatter[] fruits = new Formatter[]
{
    new Formatter("bananas", Color.LightGoldenrodYellow),
    new Formatter("strawberries", Color.Pink),
    new Formatter("mangoes", Color.PeachPuff),
    new Formatter("pineapples", Color.Yellow),
    new Formatter("cherries", Color.Red),
    new Formatter("oranges", Color.Orange),
    new Formatter("apples", Color.LawnGreen),
    new Formatter("peaches", Color.MistyRose),
    new Formatter("plums", Color.Indigo),
    new Formatter("melons", Color.LightGreen),
};

Console.WriteLineFormatted(dream, Color.Gray, fruits);`

If we modify this line:
`string dream = "a dream of {0} and {1} and {2} and {3} and {4} and {5} and {6} and {7} and {8} and {9}...";`
into:
`string dream = "a dream of {0} and {0} and {0} and {0} and {0} and {0} and {6} and {7} and {8} and {9}...";`
the outputs are the same, instead of having the string"strawberries" repeated 6 times.

In fact, you can even scramble the indexes around and their order won't be respected.

**Comment by tomakita** [comment]
Thanks for reporting -- this is a bug.  I'll work on a fix!

**Comment by tomakita** [comment]
Fixed in https://github.com/tomakita/Colorful.Console/commit/f0d8303b80d21201f332913c289157461eb41f48 and NuGet package [v.1.1.2](https://www.nuget.org/packages/Colorful.Console)!

**Comment by IneedHelp** [comment]
Thank you for the update!
