### ISSUE TITLE
.NET Core 2.0

### ISSUE THREAD

**Issue by dotnetshadow** [tomakita/Colorful.Console#40]
Hi there, 

Just wondering if this project should be working under .NET Core 2.0?

`error CS0433: The type 'Color' exists in both 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

I'm getting the following error:
https://github.com/CoreCompat/System.Drawing/issues/4

**Comment by tomakita** [comment]
Thanks to @JamieG, Colorful.Console should now work under .NET Core 2.0!  Please feel free to open another issue if you run into problems under .NET Core 2.0.

[Colorful.Console Release 1.2.0](https://github.com/tomakita/Colorful.Console/releases/tag/1.2.0)
[NuGet package](https://www.nuget.org/packages/Colorful.Console)
