### ISSUE TITLE
Resetting colors to its defaults

### ISSUE THREAD

**Issue by Zoltraks** [tomakita/Colorful.Console#44]
There is a hint in documentation to use Colorful.Console.ReplaceAllColorsWithDefaults if we want to set colors back to defaults but this method is marked private and not accessible.

What about simple Reset() method or implementing resetting colors in Clear() method?

**Comment by tomakita** [comment]
The public version was removed on purpose, but I meant to add it again, and I never did.  I'll push a fix for this tomorrow -- sorry for the inconvenience!

**Comment by tomakita** [comment]
I've just made this fix, and `Colorful.Console.ReplaceAllColorsWithDefaults` is now publicly accessible.  Thanks again for reporting this!

Commit: https://github.com/tomakita/Colorful.Console/commit/5e47debd954fb844383b5147735069b1d99d3e83
NuGet: https://www.nuget.org/packages/Colorful.Console/1.2.2
