### ISSUE TITLE
Unfortunately, Colorful.Console does NOT render correctly on Mac

### ISSUE THREAD

**Issue by jasonvogel** [tomakita/Colorful.Console#47]
Even the simplest test fails to render correctly on the Mac. Standard Console.ForegroundColor = ConsoleColor.Red works, but not the Colorful equivalent.

I was really excited when I first found this library.

**Comment by AlexejheroYTB** [comment]
Duplicate of #46

**Comment by tomakita** [comment]
Thanks for the report.  Closing as duplicate, for now.
