### ISSUE TITLE
IndexOutOfRangeException on calling WriteLineFormatted()

### ISSUE THREAD

**Issue by LiteOnE** [tomakita/Colorful.Console#48]
So if you pass List<> as `args` argument, you'll get the exception.

It can be easily fixed using List<>.ToArray(), but anyway consider to take a look at this

**Comment by Chandler-Davidson** [comment]
I think this could be improved upon as a whole, I'd be interested in taking on some refactoring to allow more dynamic and generic uses. ConTabs is a great example of such.

**Comment by tomakita** [comment]
Thanks for reporting this -- @Chandler-Davidson has just made a contribution that allows for any implementor of IEnumerable<T> to be supplied to WriteLineFormatted.  Thanks to both of you!
