### ISSUE TITLE
Would it be possible to get a printed list of all the available colors?

### ISSUE THREAD

**Issue by crhistianramirez** [tomakita/Colorful.Console#54]
Might be nice for people trying this library out. I ended up just logging a bunch, which worked OK.

**Comment by equin0x80** [comment]
I believe it just uses the standard .NET Color enumeration, so:
string[] s = Enum.GetNames(typeof(System.Drawing.Color));

**Comment by tomakita** [comment]
Thanks @equin0x80 !  Yes, any System.Drawing.Color is usable.
