### ISSUE TITLE
Changing Color for certain text in Console.WriteLine?

### ISSUE THREAD

**Issue by zix3r** [tomakita/Colorful.Console#78]
So basically I want to do something like this:
![image](https://user-images.githubusercontent.com/43238887/95174400-acdac380-07c2-11eb-90bd-f5479b495417.png)
But in Console.WriteLine since it can mix up with other output when I use this code:
`
Console.Write(@"[", Color.Cyan);

Console.Write(0.5, Color.Yellow);

Console.Write(@"] ", Color.Cyan);

Console.Write(@"Code: ", Color.Orange);

Console.Write("test");

Console.Write(" [", Color.Cyan);

Console.Write(status, Color.Lime);

Console.WriteLine("]", Color.Cyan);
`

**Comment by tomakita** [comment]
Hi @zix3r,

Thanks for the question.  You should be able to do this using a `StyleSheet ` and `WriteLineStyled`:

    StyleSheet styleSheet = new StyleSheet(Color.White);
    styleSheet.AddStyle("[\\[\\]test]", Color.Cyan);
    styleSheet.AddStyle("0\\.5", Color.Yellow);
    styleSheet.AddStyle("Code:", Color.Orange);

    Console.WriteLineStyled("[0.5] Code: test []", styleSheet);

Note that the string argument to `StyleSheet.AddStyle` is a regular expression.

There's also another overload for `AddStyle` that allows you to pass a function that determines how the coloring happens -- see `Examples.cs` for an example: https://github.com/tomakita/Colorful.Console/blob/master/src/ExampleConsoleApplication/Examples.cs#L184

I hope that helps!

**Comment by zix3r** [comment]
Thanks a lot! Your help is appreciated!
