### ISSUE TITLE
Doesn't work by default with JetBrains Rider (due to a issue in Rider)

### ISSUE THREAD

**Issue by hmemcpy** [tomakita/Colorful.Console#8]
As you may know, JetBrains announced a .NET IDE of their own called [Rider](https://www.jetbrains.com/rider/), which is based on the IntelliJ platform.
By default, when launching console applications, Rider redirects the output to its own Output pane, rather than launching the actual console.

This causes Colorful.Console to throw:

```
Unhandled Exception: Colorful.ColorMappingException: Color conversion failed with system error code 6!
 at Colorful.ColorMapper.MapColor(ConsoleColor color, UInt32 r, UInt32 g, UInt32 b)
 at Colorful.ColorMapper.MapColor(ConsoleColor oldColor, Color newColor)
 at Colorful.ColorManager.GetConsoleColor(Color color)
 at Colorful.Console.MapToScreen(StyledString styledString, String trailer)
 at Colorful.Console.WriteAsciiInColorStyled(String trailer, StyledString target, StyleSheet styleSheet)
 at Colorful.Console.WriteLineStyled(StyledString value, StyleSheet styleSheet)
 at Colorful.Console.WriteAsciiStyled(String value, FigletFont font, StyleSheet styleSheet)
 at Program.Main(String[] args)
```

The "6" comes from Marshal.GetLastWin32Error(), and it's the value for invalid handle. Looking at the library's source, I see the source of the error here: https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorMapper.cs#L107

My best guess, is since Rider's Output window is not a real console, it doesn't have a handle, and the library fails because of it.

I'm not sure what can be done about this, but I wanted to give you heads up about it, and let you know that I've also submitted this bug to JetBrains here: https://youtrack.jetbrains.com/issue/RIDER-389

**Comment by tomakita** [comment]
Thanks for the heads-up.  I'll keep an eye on the thread that you linked to on the JetBrains forum!

**Comment by fleed** [comment]
I have the same issue running a console application in docker (Windows Server 2016 / base image `dotnet-framework:latest`). Any plan to fix it?

**Comment by tomakita** [comment]
Thanks for letting me know.  I don't think I'm going to be able to fix this entirely, i.e. I don't think I can support all of the Colorful.Console functionality in Rider and Docker.  However, would it be helpful if Colorful.Console could detect when it isn't running in a Windows console (e.g. in Rider or Docker), and simply turn off its enhanced color palette?  This would make Colorful.Console less colorful, but the other styling functionality would remain.  If this would be useful, I can look into it.

**Comment by fleed** [comment]
Thanks for replying.
Detecting "unusual" environments like docker and disabling advanced functionalies is an acceptable compromise in my opinion.

**Comment by tomakita** [comment]
Sounds good.  I'm reopening this, and will start looking into it.  I'll update this thread when there's something to report!

**Comment by tomakita** [comment]
This should be fixed in [1.0.7](https://github.com/tomakita/Colorful.Console/tree/1.0.7).  You should be able to use Colorful.Console from Rider and Docker now (and from any other application, for that matter), but without support for the full RGB color palette.  

I don't have Rider or Docker, so I wasn't able to test this fix for the two specific use cases mentioned in this thread, but it does seem to have fixed the issue in my test setup (calling Colorful.Console from a WPF application).  Let me know how this works.

**Comment by fleed** [comment]
Version `1.0.7` for me under Docker. Thank you!

**Comment by tomakita** [comment]
Cool!
